<?php

namespace Database\Seeders;

use App\Models\City;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            [
                'name'         => 'Johor Bahru',
                'display_name' => 'Johor Bahru',
                'state_id'     => 1,
                'code'         => 'Johor',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tebrau',
                'display_name' => 'Tebrau',
                'state_id'     => 1,
                'code'         => 'Tebrau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pasir Gudang',
                'display_name' => 'Pasir Gudang',
                'state_id'     => 1,
                'code'         => 'Pasir',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Indah',
                'display_name' => 'Bukit Indah',
                'state_id'     => 1,
                'code'         => 'Bukit',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Skudai',
                'display_name' => 'Skudai',
                'state_id'     => 1,
                'code'         => 'Skudai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kluang',
                'display_name' => 'Kluang',
                'state_id'     => 1,
                'code'         => 'Kluang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batu Pahat',
                'display_name' => 'Batu Pahat',
                'state_id'     => 1,
                'code'         => 'Batu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Muar',
                'display_name' => 'Muar',
                'state_id'     => 1,
                'code'         => 'Muar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ulu Tiram',
                'display_name' => 'Ulu Tiram',
                'state_id'     => 1,
                'code'         => 'Ulu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Senai',
                'display_name' => 'Senai',
                'state_id'     => 1,
                'code'         => 'Senai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Segamat',
                'display_name' => 'Segamat',
                'state_id'     => 1,
                'code'         => 'Segamat',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kulai',
                'display_name' => 'Kulai',
                'state_id'     => 1,
                'code'         => 'Kulai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kota Tinggi',
                'display_name' => 'Kota Tinggi',
                'state_id'     => 1,
                'code'         => 'Kota',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pontian Kechil',
                'display_name' => 'Pontian Kechil',
                'state_id'     => 1,
                'code'         => 'Pontian',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tangkak',
                'display_name' => 'Tangkak',
                'state_id'     => 1,
                'code'         => 'Tangkak',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Bakri',
                'display_name' => 'Bukit Bakri',
                'state_id'     => 1,
                'code'         => 'Bukit',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Yong Peng',
                'display_name' => 'Yong Peng',
                'state_id'     => 1,
                'code'         => 'Yong',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pekan Nenas',
                'display_name' => 'Pekan Nenas',
                'state_id'     => 1,
                'code'         => 'Pekan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Labis',
                'display_name' => 'Labis',
                'state_id'     => 1,
                'code'         => 'Labis',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Mersing',
                'display_name' => 'Mersing',
                'state_id'     => 1,
                'code'         => 'Mersing',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Simpang Renggam',
                'display_name' => 'Simpang Renggam',
                'state_id'     => 1,
                'code'         => 'Simpang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Parit Raja',
                'display_name' => 'Parit Raja',
                'state_id'     => 1,
                'code'         => 'Parit',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kelapa Sawit',
                'display_name' => 'Kelapa Sawit',
                'state_id'     => 1,
                'code'         => 'Kelapa',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Buloh Kasap',
                'display_name' => 'Buloh Kasap',
                'state_id'     => 1,
                'code'         => 'Buloh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Chaah',
                'display_name' => 'Chaah',
                'state_id'     => 1,
                'code'         => 'Chaah',
                'country_id'   => 1,
            ],

            
            [
                'name'         => 'Sungai Petani',
                'display_name' => 'Sungai Petani',
                'state_id'     => 2,
                'code'         => 'Sungai Peta,ni',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Alor Setar',
                'display_name' => 'Alor Setar',
                'state_id'     => 2,
                'code'         => 'Alor Setar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kulim',
                'display_name' => 'Kulim',
                'state_id'     => 2,
                'code'         => 'Kulim',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Jitra',
                'display_name' => 'Jitra',
                'state_id'     => 2,
                'code'         => 'Jitra',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Baling',
                'display_name' => 'Baling',
                'state_id'     => 2,
                'code'         => 'Baling',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pendang',
                'display_name' => 'Pendang',
                'state_id'     => 2,
                'code'         => 'Pendang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Langkawi',
                'display_name' => 'Langkawi',
                'state_id'     => 2,
                'code'         => 'Langkawi',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Yan',
                'display_name' => 'Yan',
                'state_id'     => 2,
                'code'         => 'Yan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sik',
                'display_name' => 'Sik',
                'state_id'     => 2,
                'code'         => 'Sik',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Nerang',
                'display_name' => 'Kuala Nerang',
                'state_id'     => 2,
                'code'         => 'Kuala Neran,g',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pokok Sena',
                'display_name' => 'Pokok Sena',
                'state_id'     => 2,
                'code'         => 'Pokok Sena',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bandar Baharu',
                'display_name' => 'Bandar Baharu',
                'state_id'     => 2,
                'code'         => 'Bandar Baha,ru',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Kota Bharu',
                'display_name' => 'Kota Bharu',
                'state_id'     => 3,
                'code'         => 'Kota Bharu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pengkalan Kubor',
                'display_name' => 'Pengkalan Kubor',
                'state_id'     => 3,
                'code'         => 'Pengkalan K,ubor',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanah Merah',
                'display_name' => 'Tanah Merah',
                'state_id'     => 3,
                'code'         => 'Tanah Merah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Peringat',
                'display_name' => 'Peringat',
                'state_id'     => 3,
                'code'         => 'Peringat',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Wakaf Bharu',
                'display_name' => 'Wakaf Bharu',
                'state_id'     => 3,
                'code'         => 'Wakaf Bharu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kadok',
                'display_name' => 'Kadok',
                'state_id'     => 3,
                'code'         => 'Kadok',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pasir Mas',
                'display_name' => 'Pasir Mas',
                'state_id'     => 3,
                'code'         => 'Pasir Mas',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Gua Musang',
                'display_name' => 'Gua Musang',
                'state_id'     => 3,
                'code'         => 'Gua Musang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Krai',
                'display_name' => 'Kuala Krai',
                'state_id'     => 3,
                'code'         => 'Kuala Krai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tumpat',
                'display_name' => 'Tumpat',
                'state_id'     => 3,
                'code'         => 'Tumpat',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Bandaraya Melaka',
                'display_name' => 'Bandaraya Melaka',
                'state_id'     => 4,
                'code'         => 'Bandaraya M,elaka',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Baru',
                'display_name' => 'Bukit Baru',
                'state_id'     => 4,
                'code'         => 'Bukit Baru',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ayer Keroh',
                'display_name' => 'Ayer Keroh',
                'state_id'     => 4,
                'code'         => 'Ayer Keroh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Klebang',
                'display_name' => 'Klebang',
                'state_id'     => 4,
                'code'         => 'Klebang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Masjid Tanah',
                'display_name' => 'Masjid Tanah',
                'state_id'     => 4,
                'code'         => 'Masjid Tana,h',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sungai Udang',
                'display_name' => 'Sungai Udang',
                'state_id'     => 4,
                'code'         => 'Sungai Udan,g',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batu Berendam',
                'display_name' => 'Batu Berendam',
                'state_id'     => 4,
                'code'         => 'Batu Berend,am',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Alor Gajah',
                'display_name' => 'Alor Gajah',
                'state_id'     => 4,
                'code'         => 'Alor Gajah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Rambai',
                'display_name' => 'Bukit Rambai',
                'state_id'     => 4,
                'code'         => 'Bukit Ramba,i',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ayer Molek',
                'display_name' => 'Ayer Molek',
                'state_id'     => 4,
                'code'         => 'Ayer Molek',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bemban',
                'display_name' => 'Bemban',
                'state_id'     => 4,
                'code'         => 'Bemban',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Sungai Baru',
                'display_name' => 'Kuala Sungai Baru',
                'state_id'     => 4,
                'code'         => 'Kuala Sunga,i Baru',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pulau Sebang',
                'display_name' => 'Pulau Sebang',
                'state_id'     => 4,
                'code'         => 'Pulau Seban,g',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Seremban',
                'display_name' => 'Seremban',
                'state_id'     => 5,
                'code'         => 'Seremban',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Port Dickson',
                'display_name' => 'Port Dickson',
                'state_id'     => 5,
                'code'         => 'Port Dickso,n',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Nilai',
                'display_name' => 'Nilai',
                'state_id'     => 5,
                'code'         => 'Nilai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bahau',
                'display_name' => 'Bahau',
                'state_id'     => 5,
                'code'         => 'Bahau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tampin',
                'display_name' => 'Tampin',
                'state_id'     => 5,
                'code'         => 'Tampin',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Pilah',
                'display_name' => 'Kuala Pilah',
                'state_id'     => 5,
                'code'         => 'Kuala Pilah',
                'country_id'   => 1,
            ],


            [
                'name'         => 'Kuantan',
                'display_name' => 'Kuantan',
                'state_id'     => 6,
                'code'         => 'Kuantan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Temerloh',
                'display_name' => 'Temerloh',
                'state_id'     => 6,
                'code'         => 'Temerloh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bentong',
                'display_name' => 'Bentong',
                'state_id'     => 6,
                'code'         => 'Bentong',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Mentakab',
                'display_name' => 'Mentakab',
                'state_id'     => 6,
                'code'         => 'Mentakab',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Raub',
                'display_name' => 'Raub',
                'state_id'     => 6,
                'code'         => 'Raub',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Jerantut',
                'display_name' => 'Jerantut',
                'state_id'     => 6,
                'code'         => 'Jerantut',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pekan',
                'display_name' => 'Pekan',
                'state_id'     => 6,
                'code'         => 'Pekan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Lipis',
                'display_name' => 'Kuala Lipis',
                'state_id'     => 6,
                'code'         => 'Kuala Lipis',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bandar Jengka',
                'display_name' => 'Bandar Jengka',
                'state_id'     => 6,
                'code'         => 'Bandar Jeng,ka',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Tinggi',
                'display_name' => 'Bukit Tinggi',
                'state_id'     => 6,
                'code'         => 'Bukit Tingg,i',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Bukit Mertajam',
                'display_name' => 'Bukit Mertajam',
                'state_id'     => 7,
                'code'         => 'Bukit Merta,jam',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Georgetown',
                'display_name' => 'Georgetown',
                'state_id'     => 7,
                'code'         => 'Georgetown',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sungai Ara',
                'display_name' => 'Sungai Ara',
                'state_id'     => 7,
                'code'         => 'Sungai Ara',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Gelugor',
                'display_name' => 'Gelugor',
                'state_id'     => 7,
                'code'         => 'Gelugor',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Air Itam',
                'display_name' => 'Air Itam',
                'state_id'     => 7,
                'code'         => 'Air Itam',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Butterworth',
                'display_name' => 'Butterworth',
                'state_id'     => 7,
                'code'         => 'Butterworth',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Perai',
                'display_name' => 'Perai',
                'state_id'     => 7,
                'code'         => 'Perai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Nibong Tebal',
                'display_name' => 'Nibong Tebal',
                'state_id'     => 7,
                'code'         => 'Nibong Teba,l',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Permatang Pauh',
                'display_name' => 'Permatang Pauh',
                'state_id'     => 7,
                'code'         => 'Permatang P,auh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanjung Tokong',
                'display_name' => 'Tanjung Tokong',
                'state_id'     => 7,
                'code'         => 'Tanjung Tok,ong',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kepala Batas',
                'display_name' => 'Kepala Batas',
                'state_id'     => 7,
                'code'         => 'Kepala Bata,s',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanjung Bungah',
                'display_name' => 'Tanjung Bungah',
                'state_id'     => 7,
                'code'         => 'Tanjung Bun,gah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Juru',
                'display_name' => 'Juru',
                'state_id'     => 7,
                'code'         => 'Juru',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Ipoh',
                'display_name' => 'Ipoh',
                'state_id'     => 8,
                'code'         => 'Ipoh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Taiping',
                'display_name' => 'Taiping',
                'state_id'     => 8,
                'code'         => 'Taiping',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sitiawan',
                'display_name' => 'Sitiawan',
                'state_id'     => 8,
                'code'         => 'Sitiawan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Simpang Empat',
                'display_name' => 'Simpang Empat',
                'state_id'     => 8,
                'code'         => 'Simpang Empat',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Teluk Intan',
                'display_name' => 'Teluk Intan',
                'state_id'     => 8,
                'code'         => 'Teluk Intan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batu Gajah',
                'display_name' => 'Batu Gajah',
                'state_id'     => 8,
                'code'         => 'Batu Gajah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Lumut',
                'display_name' => 'Lumut',
                'state_id'     => 8,
                'code'         => 'Lumut',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kampung Koh',
                'display_name' => 'Kampung Koh',
                'state_id'     => 8,
                'code'         => 'Kampung Koh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Kangsar',
                'display_name' => 'Kuala Kangsar',
                'state_id'     => 8,
                'code'         => 'Kuala Kangar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sungai Siput',
                'display_name' => 'Sungai Siput',
                'state_id'     => 8,
                'code'         => 'Sungai Siput',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tapah',
                'display_name' => 'Tapah',
                'state_id'     => 8,
                'code'         => 'Tapah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bidor',
                'display_name' => 'Bidor',
                'state_id'     => 8,
                'code'         => 'Bidor',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Parit Buntar',
                'display_name' => 'Parit Buntar',
                'state_id'     => 8,
                'code'         => 'Parit Buntar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ayer Tawar',
                'display_name' => 'Ayer Tawar',
                'state_id'     => 8,
                'code'         => 'Ayer Tawar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bagan Serai',
                'display_name' => 'Bagan Serai',
                'state_id'     => 8,
                'code'         => 'Bagan Serai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanjung Malim',
                'display_name' => 'Tanjung Malim',
                'state_id'     => 8,
                'code'         => 'Tanjung Malim',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Lawan Kuda Baharu',
                'display_name' => 'Lawan Kuda Baharu',
                'state_id'     => 8,
                'code'         => 'Lawan Kuda Baharu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pantai Remis',
                'display_name' => 'Pantai Remis',
                'state_id'     => 8,
                'code'         => 'Pantai Remis',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kampar',
                'display_name' => 'Kampar',
                'state_id'     => 8,
                'code'         => 'Kampar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kampung Gajah',
                'display_name' => 'Kampung Gajah',
                'state_id'     => 8,
                'code'         => 'Kampung Gajah',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Kangar',
                'display_name' => 'Kangar',
                'state_id'     => 9,
                'code'         => 'Kangar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Arau',
                'display_name' => 'Arau',
                'state_id'     => 9,
                'code'         => 'Arau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Padang Besar',
                'display_name' => 'Padang Besar',
                'state_id'     => 9,
                'code'         => 'Padang Besa,r',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Subang Jaya',
                'display_name' => 'Subang Jaya',
                'state_id'     => 10,
                'code'         => 'Subang Jaya',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Klang',
                'display_name' => 'Klang',
                'state_id'     => 10,
                'code'         => 'Klang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ampang Jaya',
                'display_name' => 'Ampang Jaya',
                'state_id'     => 10,
                'code'         => 'Ampang Jaya',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bangi',
                'display_name' => 'Bangi',
                'state_id'     => 10,
                'code'         => 'Bangi',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bandar Baru Bangi',
                'display_name' => 'Bandar Baru Bangi',
                'state_id'     => 10,
                'code'         => 'Bandar Baru, Bangi',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Shah Alam',
                'display_name' => 'Shah Alam',
                'state_id'     => 10,
                'code'         => 'Shah Alam',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Petaling Jaya',
                'display_name' => 'Petaling Jaya',
                'state_id'     => 10,
                'code'         => 'Petaling Ja,ya',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Cheras',
                'display_name' => 'Cheras',
                'state_id'     => 10,
                'code'         => 'Cheras',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kajang',
                'display_name' => 'Kajang',
                'state_id'     => 10,
                'code'         => 'Kajang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Selayang',
                'display_name' => 'Selayang',
                'state_id'     => 10,
                'code'         => 'Selayang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Rawang',
                'display_name' => 'Rawang',
                'state_id'     => 10,
                'code'         => 'Rawang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Taman Greenwood',
                'display_name' => 'Taman Greenwood',
                'state_id'     => 10,
                'code'         => 'Taman Green,wood',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Semenyih',
                'display_name' => 'Semenyih',
                'state_id'     => 10,
                'code'         => 'Semenyih',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Banting',
                'display_name' => 'Banting',
                'state_id'     => 10,
                'code'         => 'Banting',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Balakong',
                'display_name' => 'Balakong',
                'state_id'     => 10,
                'code'         => 'Balakong',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Gombak Setia',
                'display_name' => 'Gombak Setia',
                'state_id'     => 10,
                'code'         => 'Gombak Seti,a',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Selangor',
                'display_name' => 'Kuala Selangor',
                'state_id'     => 10,
                'code'         => 'Kuala Selan,gor',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Serendah',
                'display_name' => 'Serendah',
                'state_id'     => 10,
                'code'         => 'Serendah',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bukit Beruntung',
                'display_name' => 'Bukit Beruntung',
                'state_id'     => 10,
                'code'         => 'Bukit Berun,tung',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Pengkalan Kundang',
                'display_name' => 'Pengkalan Kundang',
                'state_id'     => 10,
                'code'         => 'Pengkalan K,undang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Jenjarom',
                'display_name' => 'Jenjarom',
                'state_id'     => 10,
                'code'         => 'Jenjarom',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sungai Besar',
                'display_name' => 'Sungai Besar',
                'state_id'     => 10,
                'code'         => 'Sungai Besa,r',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batu Arang',
                'display_name' => 'Batu Arang',
                'state_id'     => 10,
                'code'         => 'Batu Arang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanjung Sepat',
                'display_name' => 'Tanjung Sepat',
                'state_id'     => 10,
                'code'         => 'Tanjung Sep,at',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuang',
                'display_name' => 'Kuang',
                'state_id'     => 10,
                'code'         => 'Kuang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Kubu Baharu',
                'display_name' => 'Kuala Kubu Baharu',
                'state_id'     => 10,
                'code'         => 'Kuala Kubu ,Baharu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batang Berjuntai',
                'display_name' => 'Batang Berjuntai',
                'state_id'     => 10,
                'code'         => 'Batang Berj,untai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bandar Baru Salak Tinggi',
                'display_name' => 'Bandar Baru Salak Tinggi',
                'state_id'     => 10,
                'code'         => 'Bandar Baru, Salak Tinggi',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sekinchan',
                'display_name' => 'Sekinchan',
                'state_id'     => 10,
                'code'         => 'Sekinchan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sabak',
                'display_name' => 'Sabak',
                'state_id'     => 10,
                'code'         => 'Sabak',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tanjung Karang',
                'display_name' => 'Tanjung Karang',
                'state_id'     => 10,
                'code'         => 'Tanjung Kar,ang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Beranang',
                'display_name' => 'Beranang',
                'state_id'     => 10,
                'code'         => 'Beranang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sungai Pelek',
                'display_name' => 'Sungai Pelek',
                'state_id'     => 10,
                'code'         => 'Sungai Pele,k',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Kuala Terengganu',
                'display_name' => 'Kuala Terengganu',
                'state_id'     => 11,
                'code'         => 'Kuala Terengganu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Chukai',
                'display_name' => 'Chukai',
                'state_id'     => 11,
                'code'         => 'Chukai',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Dungun',
                'display_name' => 'Dungun',
                'state_id'     => 11,
                'code'         => 'Dungun',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kerteh',
                'display_name' => 'Kerteh',
                'state_id'     => 11,
                'code'         => 'Kerteh',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kuala Berang',
                'display_name' => 'Kuala Berang',
                'state_id'     => 11,
                'code'         => 'Kuala Berang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Marang',
                'display_name' => 'Marang',
                'state_id'     => 11,
                'code'         => 'Marang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Paka',
                'display_name' => 'Paka',
                'state_id'     => 11,
                'code'         => 'Paka',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Jerteh',
                'display_name' => 'Jerteh',
                'state_id'     => 11,
                'code'         => 'Jerteh',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Kota Kinabalu',
                'display_name' => 'Kota Kinabalu',
                'state_id'     => 12,
                'code'         => 'Kota Kinaba,lu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sandakan',
                'display_name' => 'Sandakan',
                'state_id'     => 12,
                'code'         => 'Sandakan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Tawau',
                'display_name' => 'Tawau',
                'state_id'     => 12,
                'code'         => 'Tawau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Lahad Datu',
                'display_name' => 'Lahad Datu',
                'state_id'     => 12,
                'code'         => 'Lahad Datu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Keningau',
                'display_name' => 'Keningau',
                'state_id'     => 12,
                'code'         => 'Keningau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Putatan',
                'display_name' => 'Putatan',
                'state_id'     => 12,
                'code'         => 'Putatan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Donggongon',
                'display_name' => 'Donggongon',
                'state_id'     => 12,
                'code'         => 'Donggongon',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Semporna',
                'display_name' => 'Semporna',
                'state_id'     => 12,
                'code'         => 'Semporna',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kudat',
                'display_name' => 'Kudat',
                'state_id'     => 12,
                'code'         => 'Kudat',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kunak',
                'display_name' => 'Kunak',
                'state_id'     => 12,
                'code'         => 'Kunak',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Papar',
                'display_name' => 'Papar',
                'state_id'     => 12,
                'code'         => 'Papar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Ranau',
                'display_name' => 'Ranau',
                'state_id'     => 12,
                'code'         => 'Ranau',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Beaufort',
                'display_name' => 'Beaufort',
                'state_id'     => 12,
                'code'         => 'Beaufort',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kinarut',
                'display_name' => 'Kinarut',
                'state_id'     => 12,
                'code'         => 'Kinarut',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kota Belud',
                'display_name' => 'Kota Belud',
                'state_id'     => 12,
                'code'         => 'Kota Belud',
                'country_id'   => 1,
            ],

            [
                'name'         => 'Kuching',
                'display_name' => 'Kuching',
                'state_id'     => 13,
                'code'         => 'Kuching',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Miri',
                'display_name' => 'Miri',
                'state_id'     => 13,
                'code'         => 'Miri',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sibu',
                'display_name' => 'Sibu',
                'state_id'     => 13,
                'code'         => 'Sibu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Bintulu',
                'display_name' => 'Bintulu',
                'state_id'     => 13,
                'code'         => 'Bintulu',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Limbang',
                'display_name' => 'Limbang',
                'state_id'     => 13,
                'code'         => 'Limbang',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sarikei',
                'display_name' => 'Sarikei',
                'state_id'     => 13,
                'code'         => 'Sarikei',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Sri Aman',
                'display_name' => 'Sri Aman',
                'state_id'     => 13,
                'code'         => 'Sri Aman',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kapit',
                'display_name' => 'Kapit',
                'state_id'     => 13,
                'code'         => 'Kapit',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Batu Delapan Bazaar',
                'display_name' => 'Batu Delapan Bazaar',
                'state_id'     => 13,
                'code'         => 'Batu Delapan Bazaar',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Kota Samarahan',
                'display_name' => 'Kota Samarahan',
                'state_id'     => 13,
                'code'         => 'Kota Samarahan',
                'country_id'   => 1,
            ],
            [
                'name'         => 'Wilayah Persekutuan Kuala Lumpur / Putrajaya / Labuan',
                'display_name' => 'Wilayah Persekutuan Kuala Lumpur / Putrajaya / Labuan',
                'state_id'     => 14,
                'code'         => 'Wilayah Per,sekutuan Kuala Lumpur / Putrajaya / Labuan',
                'country_id'   => 1,
            ],
        ];

        foreach ($cities as $city) {
            City::updateOrInsert(['display_name' => $city['display_name'], 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()], $city);
        }
    }
}
