<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'id' => 114,
                'code' => 'AFGHANISTAN',
                'name' => 'AFGHANISTAN',
                'display_name' => 'AFGHANISTAN',
            ],
            [
                'id' => 2,
                'code' => 'ALBANIA',
                'name' => 'ALBANIA',
                'display_name' => 'ALBANIA',
            ],
            [
                'id' => 3,
                'code' => 'ALGERIA',
                'name' => 'ALGERIA',
                'display_name' => 'ALGERIA',
            ],
            [
                'id' => 4,
                'code' => 'ANGOLA',
                'name' => 'ANGOLA',
                'display_name' => 'ANGOLA',
            ],
            [
                'id' => 5,
                'code' => 'ANGUILLA',
                'name' => 'ANGUILLA',
                'display_name' => 'ANGUILLA',
            ],
            [
                'id' => 6,
                'code' => 'ANTIGUA',
                'name' => 'ANTIGUA',
                'display_name' => 'ANTIGUA',
            ],
            [
                'id' => 7,
                'code' => 'ARGENTINA',
                'name' => 'ARGENTINA',
                'display_name' => 'ARGENTINA',
            ],
            [
                'id' => 8,
                'code' => 'AUSTRALIA',
                'name' => 'AUSTRALIA',
                'display_name' => 'AUSTRALIA',
            ],
            [
                'id' => 9,
                'code' => 'AUSTRIA',
                'name' => 'AUSTRIA',
                'display_name' => 'AUSTRIA',
            ],
            [
                'id' => 10,
                'code' => 'ARMENIA',
                'name' => 'ARMENIA',
                'display_name' => 'ARMENIA',
            ],
            [
                'id' => 11,
                'code' => 'AZERBAIJAN',
                'name' => 'AZERBAIJAN',
                'display_name' => 'AZERBAIJAN',
            ],
            [
                'id' => 12,
                'code' => 'BAHAMAS',
                'name' => 'BAHAMAS',
                'display_name' => 'BAHAMAS',
            ],
            [
                'id' => 13,
                'code' => 'BAHRAIN',
                'name' => 'BAHRAIN',
                'display_name' => 'BAHRAIN',
            ],
            [
                'id' => 14,
                'code' => 'BANGLADESH',
                'name' => 'BANGLADESH',
                'display_name' => 'BANGLADESH',
            ],
            [
                'id' => 15,
                'code' => 'BARBADOS',
                'name' => 'BARBADOS',
                'display_name' => 'BARBADOS',
            ],
            [
                'id' => 16,
                'code' => 'BELGIUM',
                'name' => 'BELGIUM',
                'display_name' => 'BELGIUM',
            ],
            [
                'id' => 17,
                'code' => 'BERMUDA',
                'name' => 'BERMUDA',
                'display_name' => 'BERMUDA',
            ],
            [
                'id' => 18,
                'code' => 'BHUTAN',
                'name' => 'BHUTAN',
                'display_name' => 'BHUTAN',
            ],
            [
                'id' => 19,
                'code' => 'BOLIVIA',
                'name' => 'BOLIVIA',
                'display_name' => 'BOLIVIA',
            ],
            [
                'id' => 20,
                'code' => 'BOTSWANA',
                'name' => 'BOTSWANA',
                'display_name' => 'BOTSWANA',
            ],
            [
                'id' => 21,
                'code' => 'BRAZIL',
                'name' => 'BRAZIL',
                'display_name' => 'BRAZIL',
            ],
            [
                'id' => 22,
                'code' => 'BRUNEI',
                'name' => 'BRUNEI',
                'display_name' => 'BRUNEI',
            ],
            [
                'id' => 23,
                'code' => 'BULGARIA',
                'name' => 'BULGARIA',
                'display_name' => 'BULGARIA',
            ],
            [
                'id' => 24,
                'code' => 'BURUNDI',
                'name' => 'BURUNDI',
                'display_name' => 'BURUNDI',
            ],
            [
                'id' => 25,
                'code' => 'BENIN',
                'name' => 'BENIN',
                'display_name' => 'BENIN',
            ],
            [
                'id' => 26,
                'code' => 'BELARUS',
                'name' => 'BELARUS',
                'display_name' => 'BELARUS',
            ],
            [
                'id' => 27,
                'code' => 'BELIZE',
                'name' => 'BELIZE',
                'display_name' => 'BELIZE',
            ],
            [
                'id' => 28,
                'code' => 'BOSNIA AND HERZEGOVINA',
                'name' => 'BOSNIA AND HERZEGOVINA',
                'display_name' => 'BOSNIA AND HERZEGOVINA',
            ],
            [
                'id' => 29,
                'code' => 'BULKINA FASO',
                'name' => 'BULKINA FASO',
                'display_name' => 'BULKINA FASO',
            ],
            [
                'id' => 30,
                'code' => 'CAMEROON',
                'name' => 'CAMEROON',
                'display_name' => 'CAMEROON',
            ],
            [
                'id' => 31,
                'code' => 'CANADA',
                'name' => 'CANADA',
                'display_name' => 'CANADA',
            ],
            [
                'id' => 32,
                'code' => 'CHAD',
                'name' => 'CHAD',
                'display_name' => 'CHAD',
            ],
            [
                'id' => 33,
                'code' => 'CHILE',
                'name' => 'CHILE',
                'display_name' => 'CHILE',
            ],
            [
                'id' => 34,
                'code' => 'CHINA P.R',
                'name' => 'CHINA P.R',
                'display_name' => 'CHINA P.R',
            ],
            [
                'id' => 35,
                'code' => 'COLOMBIA',
                'name' => 'COLOMBIA',
                'display_name' => 'COLOMBIA',
            ],
            [
                'id' => 36,
                'code' => 'CONGO',
                'name' => 'CONGO',
                'display_name' => 'CONGO',
            ],
            [
                'id' => 37,
                'code' => 'COSTA RICA',
                'name' => 'COSTA RICA',
                'display_name' => 'COSTA RICA',
            ],
            [
                'id' => 38,
                'code' => 'CUBA',
                'name' => 'CUBA',
                'display_name' => 'CUBA',
            ],
            [
                'id' => 39,
                'code' => 'CYPRUS',
                'name' => 'CYPRUS',
                'display_name' => 'CYPRUS',
            ],
            [
                'id' => 40,
                'code' => 'CZECH',
                'name' => 'CZECH',
                'display_name' => 'CZECH',
            ],
            [
                'id' => 41,
                'code' => 'CROATIA',
                'name' => 'CROATIA',
                'display_name' => 'CROATIA',
            ],
            [
                'id' => 42,
                'code' => 'CAMBODIA',
                'name' => 'CAMBODIA',
                'display_name' => 'CAMBODIA',
            ],
            [
                'id' => 43,
                'code' => 'COMOROS',
                'name' => 'COMOROS',
                'display_name' => 'COMOROS',
            ],
            [
                'id' => 44,
                'code' => 'CHECHNYA',
                'name' => 'CHECHNYA',
                'display_name' => 'CHECHNYA',
            ],
            [
                'id' => 45,
                'code' => 'CENTRAL AFRICAN REPUBLIC',
                'name' => 'CENTRAL AFRICAN REPUBLIC',
                'display_name' => 'CENTRAL AFRICAN REPUBLIC',
            ],
            [
                'id' => 46,
                'code' => 'CAPE VERDE',
                'name' => 'CAPE VERDE',
                'display_name' => 'CAPE VERDE',
            ],
            [
                'id' => 47,
                'code' => 'COOK ISLANDS',
                'name' => 'COOK ISLANDS',
                'display_name' => 'COOK ISLANDS',
            ],
            [
                'id' => 48,
                'code' => 'CASTRIES',
                'name' => 'CASTRIES',
                'display_name' => 'CASTRIES',
            ],
            [
                'id' => 49,
                'code' => 'CURACAO',
                'name' => 'CURACAO',
                'display_name' => 'CURACAO',
            ],
            [
                'id' => 50,
                'code' => 'DAHOMEY',
                'name' => 'DAHOMEY',
                'display_name' => 'DAHOMEY',
            ],
            [
                'id' => 51,
                'code' => 'DENMARK',
                'name' => 'DENMARK',
                'display_name' => 'DENMARK',
            ],
            [
                'id' => 52,
                'code' => 'DOMINICA',
                'name' => 'DOMINICA',
                'display_name' => 'DOMINICA',
            ],
            [
                'id' => 53,
                'code' => 'DJIBOUTI',
                'name' => 'DJIBOUTI',
                'display_name' => 'DJIBOUTI',
            ],
            [
                'id' => 54,
                'code' => 'ECUADOR',
                'name' => 'ECUADOR',
                'display_name' => 'ECUADOR',
            ],
            [
                'id' => 55,
                'code' => 'EGYPT',
                'name' => 'EGYPT',
                'display_name' => 'EGYPT',
            ],
            [
                'id' => 56,
                'code' => 'EL SALVADOR',
                'name' => 'EL SALVADOR',
                'display_name' => 'EL SALVADOR',
            ],
            [
                'id' => 57,
                'code' => 'ETHIOPIA',
                'name' => 'ETHIOPIA',
                'display_name' => 'ETHIOPIA',
            ],
            [
                'id' => 58,
                'code' => 'ERITREA',
                'name' => 'ERITREA',
                'display_name' => 'ERITREA',
            ],
            [
                'id' => 59,
                'code' => 'ESTONIA',
                'name' => 'ESTONIA',
                'display_name' => 'ESTONIA',
            ],
            [
                'id' => 60,
                'code' => 'EAST TIMOR',
                'name' => 'EAST TIMOR',
                'display_name' => 'EAST TIMOR',
            ],
            [
                'id' => 61,
                'code' => 'FIJI',
                'name' => 'FIJI',
                'display_name' => 'FIJI',
            ],
            [
                'id' => 62,
                'code' => 'FINLAND',
                'name' => 'FINLAND',
                'display_name' => 'FINLAND',
            ],
            [
                'id' => 63,
                'code' => 'FRANCE',
                'name' => 'FRANCE',
                'display_name' => 'FRANCE',
            ],
            [
                'id' => 64,
                'code' => 'FRENCH POLYNESIA',
                'name' => 'FRENCH POLYNESIA',
                'display_name' => 'FRENCH POLYNESIA',
            ],
            [
                'id' => 65,
                'code' => 'GABON',
                'name' => 'GABON',
                'display_name' => 'GABON',
            ],
            [
                'id' => 66,
                'code' => 'GUAM',
                'name' => 'GUAM',
                'display_name' => 'GUAM',
            ],
            [
                'id' => 67,
                'code' => 'GERMANY',
                'name' => 'GERMANY',
                'display_name' => 'GERMANY',
            ],
            [
                'id' => 68,
                'code' => 'GHANA',
                'name' => 'GHANA',
                'display_name' => 'GHANA',
            ],
            [
                'id' => 69,
                'code' => 'GIBRALTAR',
                'name' => 'GIBRALTAR',
                'display_name' => 'GIBRALTAR',
            ],
            [
                'id' => 70,
                'code' => 'GREECE',
                'name' => 'GREECE',
                'display_name' => 'GREECE',
            ],
            [
                'id' => 71,
                'code' => 'GRENADA',
                'name' => 'GRENADA',
                'display_name' => 'GRENADA',
            ],
            [
                'id' => 72,
                'code' => 'GUATEMALA',
                'name' => 'GUATEMALA',
                'display_name' => 'GUATEMALA',
            ],
            [
                'id' => 73,
                'code' => 'GUINEA',
                'name' => 'GUINEA',
                'display_name' => 'GUINEA',
            ],
            [
                'id' => 74,
                'code' => 'GUYANA',
                'name' => 'GUYANA',
                'display_name' => 'GUYANA',
            ],
            [
                'id' => 75,
                'code' => 'GAMBIA',
                'name' => 'GAMBIA',
                'display_name' => 'GAMBIA',
            ],
            [
                'id' => 76,
                'code' => 'GEORGIA',
                'name' => 'GEORGIA',
                'display_name' => 'GEORGIA',
            ],
            [
                'id' => 77,
                'code' => 'GERMANY, DEMOCRATIC REP. OF',
                'name' => 'GERMANY, DEMOCRATIC REP. OF',
                'display_name' => 'GERMANY, DEMOCRATIC REP. OF',
            ],
            [
                'id' => 78,
                'code' => 'GUINEA BISSAU',
                'name' => 'GUINEA BISSAU',
                'display_name' => 'GUINEA BISSAU',
            ],
            [
                'id' => 79,
                'code' => 'GUADELOUPE',
                'name' => 'GUADELOUPE',
                'display_name' => 'GUADELOUPE',
            ],
            [
                'id' => 80,
                'code' => 'HAITI',
                'name' => 'HAITI',
                'display_name' => 'HAITI',
            ],
            [
                'id' => 81,
                'code' => 'HONDURAS',
                'name' => 'HONDURAS',
                'display_name' => 'HONDURAS',
            ],
            [
                'id' => 82,
                'code' => 'HONG KONG',
                'name' => 'HONG KONG',
                'display_name' => 'HONG KONG',
            ],
            [
                'id' => 83,
                'code' => 'HUNGARY',
                'name' => 'HUNGARY',
                'display_name' => 'HUNGARY',
            ],
            [
                'id' => 84,
                'code' => 'ICELAND',
                'name' => 'ICELAND',
                'display_name' => 'ICELAND',
            ],
            [
                'id' => 85,
                'code' => 'INDIA',
                'name' => 'INDIA',
                'display_name' => 'INDIA',
            ],
            [
                'id' => 86,
                'code' => 'INDONESIA',
                'name' => 'INDONESIA',
                'display_name' => 'INDONESIA',
            ],
            [
                'id' => 87,
                'code' => 'IRAN',
                'name' => 'IRAN',
                'display_name' => 'IRAN',
            ],
            [
                'id' => 88,
                'code' => 'IRAQ',
                'name' => 'IRAQ',
                'display_name' => 'IRAQ',
            ],
            [
                'id' => 89,
                'code' => 'IRELAND REP.',
                'name' => 'IRELAND REP.',
                'display_name' => 'IRELAND REP.',
            ],
            [
                'id' => 90,
                'code' => 'ISRAEL',
                'name' => 'ISRAEL',
                'display_name' => 'ISRAEL',
            ],
            [
                'id' => 91,
                'code' => 'ITALY',
                'name' => 'ITALY',
                'display_name' => 'ITALY',
            ],
            [
                'id' => 92,
                'code' => "COTE D'IVOIRE",
                'name' => "COTE D'IVOIRE",
                'display_name' => "COTE D'IVOIRE",
            ],
            [
                'id' => 93,
                'code' => 'JAMAICA',
                'name' => 'JAMAICA',
                'display_name' => 'JAMAICA',
            ],
            [
                'id' => 94,
                'code' => 'JAPAN',
                'name' => 'JAPAN',
                'display_name' => 'JAPAN',
            ],
            [
                'id' => 95,
                'code' => 'JORDAN',
                'name' => 'JORDAN',
                'display_name' => 'JORDAN',
            ],
            [
                'id' => 96,
                'code' => 'KENYA',
                'name' => 'KENYA',
                'display_name' => 'KENYA',
            ],
            [
                'id' => 97,
                'code' => 'NORTH KOREA',
                'name' => 'NORTH KOREA',
                'display_name' => 'NORTH KOREA',
            ],
            [
                'id' => 98,
                'code' => 'SOUTH KOREA',
                'name' => 'SOUTH KOREA',
                'display_name' => 'SOUTH KOREA',
            ],
            [
                'id' => 99,
                'code' => 'KUWAIT',
                'name' => 'KUWAIT',
                'display_name' => 'KUWAIT',
            ],
            [
                'id' => 100,
                'code' => 'KAZAKHSTAN',
                'name' => 'KAZAKHSTAN',
                'display_name' => 'KAZAKHSTAN',
            ],
            [
                'id' => 101,
                'code' => 'KYRGYZSTAN',
                'name' => 'KYRGYZSTAN',
                'display_name' => 'KYRGYZSTAN',
            ],
            [
                'id' => 102,
                'code' => 'KIRIBATI',
                'name' => 'KIRIBATI',
                'display_name' => 'KIRIBATI',
            ],
            [
                'id' => 103,
                'code' => 'KIRIBATI',
                'name' => 'KIRIBATI',
                'display_name' => 'KIRIBATI',
            ],
            [
                'id' => 104,
                'code' => 'LAOS',
                'name' => 'LAOS',
                'display_name' => 'LAOS',
            ],
            [
                'id' => 105,
                'code' => 'LEBANON',
                'name' => 'LEBANON',
                'display_name' => 'LEBANON',
            ],
            [
                'id' => 106,
                'code' => 'LESOTHO',
                'name' => 'LESOTHO',
                'display_name' => 'LESOTHO',
            ],
            [
                'id' => 107,
                'code' => 'LIBERIA',
                'name' => 'LIBERIA',
                'display_name' => 'LIBERIA',
            ],
            [
                'id' => 108,
                'code' => 'LIBYA',
                'name' => 'LIBYA',
                'display_name' => 'LIBYA',
            ],
            [
                'id' => 109,
                'code' => 'LIECHTENSTEIN',
                'name' => 'LIECHTENSTEIN',
                'display_name' => 'LIECHTENSTEIN',
            ],
            [
                'id' => 110,
                'code' => 'LUXEMBOURG',
                'name' => 'LUXEMBOURG',
                'display_name' => 'LUXEMBOURG',
            ],
            [
                'id' => 111,
                'code' => 'LATVIA',
                'name' => 'LATVIA',
                'display_name' => 'LATVIA',
            ],
            [
                'id' => 112,
                'code' => 'LITHUANIA',
                'name' => 'LITHUANIA',
                'display_name' => 'LITHUANIA',
            ],
            [
                'id' => 113,
                'code' => 'MALAWI',
                'name' => 'MALAWI',
                'display_name' => 'MALAWI',
            ],
            [
                'id' => 1,
                'code' => 'MALAYSIA',
                'name' => 'MALAYSIA',
                'display_name' => 'MALAYSIA',
            ],
            [
                'id' => 115,
                'code' => 'MALI',
                'name' => 'MALI',
                'display_name' => 'MALI',
            ],
            [
                'id' => 116,
                'code' => 'MALTA',
                'name' => 'MALTA',
                'display_name' => 'MALTA',
            ],
            [
                'id' => 117,
                'code' => 'MAURITANIA',
                'name' => 'MAURITANIA',
                'display_name' => 'MAURITANIA',
            ],
            [
                'id' => 118,
                'code' => 'MAURITIUS',
                'name' => 'MAURITIUS',
                'display_name' => 'MAURITIUS',
            ],
            [
                'id' => 119,
                'code' => 'MEXICO',
                'name' => 'MEXICO',
                'display_name' => 'MEXICO',
            ],
            [
                'id' => 120,
                'code' => 'MONACO',
                'name' => 'MONACO',
                'display_name' => 'MONACO',
            ],
            [
                'id' => 121,
                'code' => 'MONGOLIA',
                'name' => 'MONGOLIA',
                'display_name' => 'MONGOLIA',
            ],
            [
                'id' => 122,
                'code' => 'MONTSERRAT',
                'name' => 'MONTSERRAT',
                'display_name' => 'MONTSERRAT',
            ],
            [
                'id' => 123,
                'code' => 'MOROCCO',
                'name' => 'MOROCCO',
                'display_name' => 'MOROCCO',
            ],
            [
                'id' => 124,
                'code' => 'MOZAMBIQUE',
                'name' => 'MOZAMBIQUE',
                'display_name' => 'MOZAMBIQUE',
            ],
            [
                'id' => 125,
                'code' => 'MALDIVES',
                'name' => 'MALDIVES',
                'display_name' => 'MALDIVES',
            ],
            [
                'id' => 126,
                'code' => 'MADAGASCAR',
                'name' => 'MADAGASCAR',
                'display_name' => 'MADAGASCAR',
            ],
            [
                'id' => 127,
                'code' => 'MOLDOVA',
                'name' => 'MOLDOVA',
                'display_name' => 'MOLDOVA',
            ],
            [
                'id' => 128,
                'code' => 'MYANMAR',
                'name' => 'MYANMAR',
                'display_name' => 'MYANMAR',
            ],
            [
                'id' => 129,
                'code' => 'MUSCAT',
                'name' => 'MUSCAT',
                'display_name' => 'MUSCAT',
            ],
            [
                'id' => 130,
                'code' => 'MACAU',
                'name' => 'MACAU',
                'display_name' => 'MACAU',
            ],
            [
                'id' => 131,
                'code' => 'MACEDONIA',
                'name' => 'MACEDONIA',
                'display_name' => 'MACEDONIA',
            ],
            [
                'id' => 132,
                'code' => 'MAYOTTE',
                'name' => 'MAYOTTE',
                'display_name' => 'MAYOTTE',
            ],
            [
                'id' => 133,
                'code' => 'MARSHALL ISLAND',
                'name' => 'MARSHALL ISLAND',
                'display_name' => 'MARSHALL ISLAND',
            ],
            [
                'id' => 134,
                'code' => 'MICRONESIA FEDERATION',
                'name' => 'MICRONESIA FEDERATION',
                'display_name' => 'MICRONESIA FEDERATION',
            ],
            [
                'id' => 135,
                'code' => 'MONTENEGRO',
                'name' => 'MONTENEGRO',
                'display_name' => 'MONTENEGRO',
            ],
            [
                'id' => 136,
                'code' => 'NAURU',
                'name' => 'NAURU',
                'display_name' => 'NAURU',
            ],
            [
                'id' => 137,
                'code' => 'NEPAL',
                'name' => 'NEPAL',
                'display_name' => 'NEPAL',
            ],
            [
                'id' => 138,
                'code' => 'NETHERLANDS',
                'name' => 'NETHERLANDS',
                'display_name' => 'NETHERLANDS',
            ],
            [
                'id' => 139,
                'code' => 'NEW ZEALAND',
                'name' => 'NEW ZEALAND',
                'display_name' => 'NEW ZEALAND',
            ],
            [
                'id' => 140,
                'code' => 'NICARAGUA',
                'name' => 'NICARAGUA',
                'display_name' => 'NICARAGUA',
            ],
            [
                'id' => 141,
                'code' => 'NIGER',
                'name' => 'NIGER',
                'display_name' => 'NIGER',
            ],
            [
                'id' => 142,
                'code' => 'NIGERIA',
                'name' => 'NIGERIA',
                'display_name' => 'NIGERIA',
            ],
            [
                'id' => 143,
                'code' => 'NORWAY',
                'name' => 'NORWAY',
                'display_name' => 'NORWAY',
            ],
            [
                'id' => 144,
                'code' => 'NAMIBIA',
                'name' => 'NAMIBIA',
                'display_name' => 'NAMIBIA',
            ],
            [
                'id' => 145,
                'code' => 'NEW CALEDONIA',
                'name' => 'NEW CALEDONIA',
                'display_name' => 'NEW CALEDONIA',
            ],
            [
                'id' => 146,
                'code' => 'NETHERLANDS ANTILLES',
                'name' => 'NETHERLANDS ANTILLES',
                'display_name' => 'NETHERLANDS ANTILLES',
            ],
            [
                'id' => 147,
                'code' => 'NORTHERN MARIANA ISLANDS',
                'name' => 'NORTHERN MARIANA ISLANDS',
                'display_name' => 'NORTHERN MARIANA ISLANDS',
            ],
            [
                'id' => 148,
                'code' => 'OMAN',
                'name' => 'OMAN',
                'display_name' => 'OMAN',
            ],
            [
                'id' => 149,
                'code' => 'PAKISTAN',
                'name' => 'PAKISTAN',
                'display_name' => 'PAKISTAN',
            ],
            [
                'id' => 150,
                'code' => 'PANAMA',
                'name' => 'PANAMA',
                'display_name' => 'PANAMA',
            ],
            [
                'id' => 151,
                'code' => 'PAPUA N GUINEA',
                'name' => 'PAPUA N GUINEA',
                'display_name' => 'PAPUA N GUINEA',
            ],
            [
                'id' => 152,
                'code' => 'PARAGUAY',
                'name' => 'PARAGUAY',
                'display_name' => 'PARAGUAY',
            ],
            [
                'id' => 153,
                'code' => 'PERU',
                'name' => 'PERU',
                'display_name' => 'PERU',
            ],
            [
                'id' => 154,
                'code' => 'PHILIPPINES',
                'name' => 'PHILIPPINES',
                'display_name' => 'PHILIPPINES',
            ],
            [
                'id' => 155,
                'code' => 'POLAND',
                'name' => 'POLAND',
                'display_name' => 'POLAND',
            ],
            [
                'id' => 156,
                'code' => 'PORTUGAL',
                'name' => 'PORTUGAL',
                'display_name' => 'PORTUGAL',
            ],
            [
                'id' => 157,
                'code' => 'PACIFIC ISLAND',
                'name' => 'PACIFIC ISLAND',
                'display_name' => 'PACIFIC ISLAND',
            ],
            [
                'id' => 158,
                'code' => 'PUERTO RICO',
                'name' => 'PUERTO RICO',
                'display_name' => 'PUERTO RICO',
            ],
            [
                'id' => 159,
                'code' => 'PALESTINE',
                'name' => 'PALESTINE',
                'display_name' => 'PALESTINE',
            ],
            [
                'id' => 160,
                'code' => 'PALAU',
                'name' => 'PALAU',
                'display_name' => 'PALAU',
            ],
            [
                'id' => 161,
                'code' => 'QATAR',
                'name' => 'QATAR',
                'display_name' => 'QATAR',
            ],
            [
                'id' => 162,
                'code' => 'RHODESIA',
                'name' => 'RHODESIA',
                'display_name' => 'RHODESIA',
            ],
            [
                'id' => 163,
                'code' => 'ROMANIA',
                'name' => 'ROMANIA',
                'display_name' => 'ROMANIA',
            ],
            [
                'id' => 164,
                'code' => 'RWANDA',
                'name' => 'RWANDA',
                'display_name' => 'RWANDA',
            ],
            [
                'id' => 165,
                'code' => 'REUNION',
                'name' => 'REUNION',
                'display_name' => 'REUNION',
            ],
            [
                'id' => 166,
                'code' => 'RUSSIA',
                'name' => 'RUSSIA',
                'display_name' => 'RUSSIA',
            ],
            [
                'id' => 167,
                'code' => 'SAMOA',
                'name' => 'SAMOA',
                'display_name' => 'SAMOA',
            ],
            [
                'id' => 168,
                'code' => 'SAN MARINO',
                'name' => 'SAN MARINO',
                'display_name' => 'SAN MARINO',
            ],
            [
                'id' => 169,
                'code' => 'SAUDI ARABIA',
                'name' => 'SAUDI ARABIA',
                'display_name' => 'SAUDI ARABIA',
            ],
            [
                'id' => 170,
                'code' => 'SENEGAL',
                'name' => 'SENEGAL',
                'display_name' => 'SENEGAL',
            ],
            [
                'id' => 171,
                'code' => 'SEYCHELLES',
                'name' => 'SEYCHELLES',
                'display_name' => 'SEYCHELLES',
            ],
            [
                'id' => 172,
                'code' => 'SIERRA LEONE',
                'name' => 'SIERRA LEONE',
                'display_name' => 'SIERRA LEONE',
            ],
            [
                'id' => 173,
                'code' => 'SINGAPORE',
                'name' => 'SINGAPORE',
                'display_name' => 'SINGAPORE',
            ],
            [
                'id' => 174,
                'code' => 'SOMALIA',
                'name' => 'SOMALIA',
                'display_name' => 'SOMALIA',
            ],
            [
                'id' => 175,
                'code' => 'SOUTH AFRICA',
                'name' => 'SOUTH AFRICA',
                'display_name' => 'SOUTH AFRICA',
            ],
            [
                'id' => 176,
                'code' => 'SPAIN',
                'name' => 'SPAIN',
                'display_name' => 'SPAIN',
            ],
            [
                'id' => 177,
                'code' => 'SRI LANKA',
                'name' => 'SRI LANKA',
                'display_name' => 'SRI LANKA',
            ],
            [
                'id' => 178,
                'code' => 'SUDAN',
                'name' => 'SUDAN',
                'display_name' => 'SUDAN',
            ],
            [
                'id' => 179,
                'code' => 'SWEDEN',
                'name' => 'SWEDEN',
                'display_name' => 'SWEDEN',
            ],
            [
                'id' => 180,
                'code' => 'SWITZERLAND',
                'name' => 'SWITZERLAND',
                'display_name' => 'SWITZERLAND',
            ],
            [
                'id' => 181,
                'code' => 'SYRIA',
                'name' => 'SYRIA',
                'display_name' => 'SYRIA',
            ],
            [
                'id' => 182,
                'code' => 'SOLOMON ISLAND',
                'name' => 'SOLOMON ISLAND',
                'display_name' => 'SOLOMON ISLAND',
            ],
            [
                'id' => 183,
                'code' => 'SLOVENIA',
                'name' => 'SLOVENIA',
                'display_name' => 'SLOVENIA',
            ],
            [
                'id' => 184,
                'code' => 'SLOVAKIA, REP.',
                'name' => 'SLOVAKIA, REP.',
                'display_name' => 'SLOVAKIA, REP.',
            ],
            [
                'id' => 185,
                'code' => 'SURINAME',
                'name' => 'SURINAME',
                'display_name' => 'SURINAME',
            ],
            [
                'id' => 186,
                'code' => 'SWAZILAND',
                'name' => 'SWAZILAND',
                'display_name' => 'SWAZILAND',
            ],
            [
                'id' => 187,
                'code' => 'SAO TOME & PRINCIPE',
                'name' => 'SAO TOME & PRINCIPE',
                'display_name' => 'SAO TOME & PRINCIPE',
            ],
            [
                'id' => 188,
                'code' => 'SERBIA AND MONTENEGRO',
                'name' => 'SERBIA AND MONTENEGRO',
                'display_name' => 'SERBIA AND MONTENEGRO',
            ],
            [
                'id' => 189,
                'code' => 'ST. LUCIA',
                'name' => 'ST. LUCIA',
                'display_name' => 'ST. LUCIA',
            ],
            [
                'id' => 190,
                'code' => 'SOUTH GEORGIA & SOUTH SANDWICH',
                'name' => 'SOUTH GEORGIA & SOUTH SANDWICH ISLAND',
                'display_name' => 'SOUTH GEORGIA & SOUTH SANDWICH ISLAND',
            ],
            [
                'id' => 191,
                'code' => 'SERBIA',
                'name' => 'SERBIA',
                'display_name' => 'SERBIA',
            ],
            [
                'id' => 192,
                'code' => 'ST. VINCENT AND THE GRENADINES',
                'name' => 'ST. VINCENT AND THE GRENADINES',
                'display_name' => 'ST. VINCENT AND THE GRENADINES',
            ],
            [
                'id' => 193,
                'code' => 'TAHITI',
                'name' => 'TAHITI',
                'display_name' => 'TAHITI',
            ],
            [
                'id' => 194,
                'code' => 'TAIWAN',
                'name' => 'TAIWAN',
                'display_name' => 'TAIWAN',
            ],
            [
                'id' => 195,
                'code' => 'TANZANIA',
                'name' => 'TANZANIA',
                'display_name' => 'TANZANIA',
            ],
            [
                'id' => 196,
                'code' => 'TURKMENISTAN',
                'name' => 'TURKMENISTAN',
                'display_name' => 'TURKMENISTAN',
            ],
            [
                'id' => 197,
                'code' => 'THAILAND',
                'name' => 'THAILAND',
                'display_name' => 'THAILAND',
            ],
            [
                'id' => 198,
                'code' => 'TOBAGO',
                'name' => 'TOBAGO',
                'display_name' => 'TOBAGO',
            ],
            [
                'id' => 199,
                'code' => 'TOGO',
                'name' => 'TOGO',
                'display_name' => 'TOGO',
            ],
            [
                'id' => 200,
                'code' => 'TONGA',
                'name' => 'TONGA',
                'display_name' => 'TONGA',
            ],
            [
                'id' => 201,
                'code' => 'TRINIDAD',
                'name' => 'TRINIDAD',
                'display_name' => 'TRINIDAD',
            ],
            [
                'id' => 202,
                'code' => 'TUNISIA',
                'name' => 'TUNISIA',
                'display_name' => 'TUNISIA',
            ],
            [
                'id' => 203,
                'code' => 'TURKEY',
                'name' => 'TURKEY',
                'display_name' => 'TURKEY',
            ],
            [
                'id' => 204,
                'code' => 'TAJIKISTAN',
                'name' => 'TAJIKISTAN',
                'display_name' => 'TAJIKISTAN',
            ],
            [
                'id' => 205,
                'code' => 'TUVALU',
                'name' => 'TUVALU',
                'display_name' => 'TUVALU',
            ],
            [
                'id' => 206,
                'code' => 'UGANDA',
                'name' => 'UGANDA',
                'display_name' => 'UGANDA',
            ],
            [
                'id' => 207,
                'code' => 'UNITED KINGDOM',
                'name' => 'UNITED KINGDOM',
                'display_name' => 'UNITED KINGDOM',
            ],
            [
                'id' => 208,
                'code' => 'U.S.A',
                'name' => 'U.S.A',
                'display_name' => 'U.S.A',
            ],
            [
                'id' => 209,
                'code' => 'URUGUAY',
                'name' => 'URUGUAY',
                'display_name' => 'URUGUAY',
            ],
            [
                'id' => 210,
                'code' => 'U.A.E',
                'name' => 'U.A.E',
                'display_name' => 'U.A.E',
            ],
            [
                'id' => 211,
                'code' => 'UKRAINE',
                'name' => 'UKRAINE',
                'display_name' => 'UKRAINE',
            ],
            [
                'id' => 212,
                'code' => 'UZBEKISTAN',
                'name' => 'UZBEKISTAN',
                'display_name' => 'UZBEKISTAN',
            ],
            [
                'id' => 213,
                'code' => 'VENEZUELA',
                'name' => 'VENEZUELA',
                'display_name' => 'VENEZUELA',
            ],
            [
                'id' => 214,
                'code' => 'VIETNAM',
                'name' => 'VIETNAM',
                'display_name' => 'VIETNAM',
            ],
            [
                'id' => 215,
                'code' => 'VANUATU',
                'name' => 'VANUATU',
                'display_name' => 'VANUATU',
            ],
            [
                'id' => 216,
                'code' => 'YEMEN ARAB REP.',
                'name' => 'YEMEN ARAB REP.',
                'display_name' => 'YEMEN ARAB REP.',
            ],
            [
                'id' => 217,
                'code' => 'YUGOSLAVIA',
                'name' => 'YUGOSLAVIA',
                'display_name' => 'YUGOSLAVIA',
            ],
            [
                'id' => 218,
                'code' => 'ZAIRE',
                'name' => 'ZAIRE',
                'display_name' => 'ZAIRE',
            ],
            [
                'id' => 219,
                'code' => 'ZAMBIA',
                'name' => 'ZAMBIA',
                'display_name' => 'ZAMBIA',
            ],
            [
                'id' => 220,
                'code' => 'ZIMBABWE',
                'name' => 'ZIMBABWE',
                'display_name' => 'ZIMBABWE',
            ],
            [
                'id' => 221,
                'code' => 'LAIN-LAIN',
                'name' => 'LAIN-LAIN',
                'display_name' => 'LAIN-LAIN',
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate([
                'name' => $country['name'],
                'display_name' => $country['name'],
                'code' => $country['code'],
            ], $country);
        }
    }
}
