<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'title'            => 'MySAW Backend',
                'description'      => 'Sistem Agihan Transit & CSR',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'live',
                'phase'            => 'change_request',
                'type_id'          => 1,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => '2024-12-01',
                'end_at'           => '2025-04-01',
                'projected_end_at' => '2025-04-01',
            ],
            [
                'title'            => 'MyWakalah Frontend',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'live',
                'phase'            => 'completed',
                'type_id'          => 1,
                'category_id'      => 1,
                'framework_id'     => 4,
                'start_at'         => '2023-01-01',
                'end_at'           => '2023-12-01',
                'projected_end_at' => '2023-12-01',
            ],
            [
                'title'            => 'MyWakalah Backend',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'live',
                'phase'            => 'completed',
                'type_id'          => 1,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => '2023-01-01',
                'end_at'           => '2023-12-01',
                'projected_end_at' => '2023-12-01',
            ],
            [
                'title'            => 'MyWakalah Mobile',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'live',
                'phase'            => 'completed',
                'type_id'          => 1,
                'category_id'      => 3,
                'framework_id'     => 2,
                'start_at'         => '2023-01-01',
                'end_at'           => '2023-12-01',
                'projected_end_at' => '2023-12-01',

            ],
            [
                'title'            => 'MyZakat Mobile',
                'description'      => 'Sistem Pembayaran Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'live',
                'phase'            => 'change_request',
                'type_id'          => 1,
                'category_id'      => 3,
                'framework_id'     => 2,
                'start_at'         => '2025-11-01',
                'end_at'           => '2026-03-01',
                'projected_end_at' => '2026-03-01',
                'version'          => '3.0',
            ],
            [
                'title'            => 'MyZakat Backend',
                'description'      => 'Sistem Pembayaran Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 1,
                'status'           => 'new',
                'phase'            => 'urs',
                'type_id'          => 1,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => '2025-11-01',
                'end_at'           => '2026-03-01',
                'projected_end_at' => '2026-03-01',
            ],
            [
                'title'            => 'I-Zakat Backend',
                'description'      => 'Sistem & Portal Permohonan Bantuan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 2,
                'status'           => 'live',
                'phase'            => 'development',
                'type_id'          => 1,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => '2024-12-01',
                'end_at'           => '2025-04-01',
                'projected_end_at' => '2025-04-01',
            ],
            [
                'title'          => 'I-Zakat Frontend',
                'description'    => 'Sistem & Portal Permohonan Bantuan Zakat',
                'ownerable_type' => 'App\Models\Organization',
                'ownerable_id'   => 2,
                'status'         => 'unicorn',
                'type_id'        => 1,
                'category_id'    => 2,
                'framework_id'   => 4,
            ],
            [
                'title'          => 'I-Zakat Mobile',
                'description'    => 'Sistem & Portal Permohonan Bantuan Zakat',
                'ownerable_type' => 'App\Models\Organization',
                'ownerable_id'   => 2,
                'status'         => 'unicorn',
                'type_id'        => 1,
                'category_id'    => 3,
                'framework_id'   => 2,
            ],
            [
                'title'          => 'E-Pay ADM',
                'ownerable_type' => 'App\Models\Organization',
                'ownerable_id'   => 2,
                'status'         => 'live',
                'phase'          => 'completed',
                'type_id'        => 1,
                'category_id'    => 2,
                'framework_id'   => 1,
            ],
            [
                'title'          => 'Ejinayat Backend',
                'description'    => 'Sistem Pengurusan Jenayah Syariah',
                'ownerable_type' => 'App\Models\Organization',
                'ownerable_id'   => 3,
                'status'         => 'live',
                'phase'          => 'completed',
                'type_id'        => 1,
                'category_id'    => 2,
                'framework_id'   => 1,
            ],
            [
                'title'          => 'Ejinayat Mobile',
                'description'    => 'Sistem Pengurusan Jenayah Syariah',
                'ownerable_type' => 'App\Models\Organization',
                'ownerable_id'   => 3,
                'status'         => 'unicorn',
                'phase'          => 'prototype',
                'type_id'        => 1,
                'category_id'    => 3,
                'framework_id'   => 2,
            ],
            [
                'title'            => 'Elios Backend',
                'description'      => 'Sistem Pengurusan Projek Saya',
                'ownerable_type'   => 'App\Models\Individual',
                'ownerable_id'     => 1,
                'status'           => 'new',
                'phase'            => 'development',
                'type_id'          => 2,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => '2025-10-01',
                'projected_end_at' => '2025-12-01',
            ],
            [
                'title'            => 'I-Wakalah Backend',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 5,
                'status'           => 'new',
                'phase'            => 'prototype',
                'type_id'          => 2,
                'category_id'      => 2,
                'framework_id'     => 1,
                'start_at'         => null,
                'projected_end_at' => null,
            ],
            [
                'title'            => 'I-Wakalah Mobile',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 5,
                'status'           => 'new',
                'phase'            => 'prototype',
                'type_id'          => 2,
                'category_id'      => 3,
                'framework_id'     => 2,
                'start_at'         => null,
                'projected_end_at' => null,
            ],
            [
                'title'            => 'I-Wakalah Frontend',
                'description'      => 'Sistem Wakalah Agihan Zakat',
                'ownerable_type'   => 'App\Models\Organization',
                'ownerable_id'     => 5,
                'status'           => 'unicorn',
                'type_id'          => 2,
                'category_id'      => 1,
                'framework_id'     => 2,
                'start_at'         => null,
                'projected_end_at' => null,
            ],
        ];
        
        foreach ($projects as $project) {
            \App\Models\Project::create($project);
        }
    }
}
